### ISSUE TITLE
--browser option broken with no argument

### ISSUE THREAD

**Issue by rjw57** [jonashaag/klaus#108]
In PR #107, the --browser (-b) option was added. Commit fab7f84d added an optional argument to the parameter but the parsing is broken. Specifically:

```console
$ klaus -b .
```
which is intended to open klaus browsing the current directory in the default browser instead interprets "." as the browser to launch. This manifests as the rather unobvious error reproduced below:
```
$ klaus -b .
WARNING: No repositories supplied -- syntax is 'klaus dir1 dir2...'.
Traceback (most recent call last):
  File "/home/rjw57/.local/bin/klaus", line 10, in <module>
    execfile(__file__)
  File "/home/rjw57/Downloads/klaus/bin/klaus", line 86, in <module>
    main()
  File "/home/rjw57/Downloads/klaus/bin/klaus", line 67, in main
    _open_browser(args)
  File "/home/rjw57/Downloads/klaus/bin/klaus", line 81, in _open_browser
    opener = webbrowser.get(args.browser).open
  File "/usr/lib64/python2.7/webbrowser.py", line 52, in get
    raise Error("could not locate runnable browser")
webbrowser.Error: could not locate runnable browser
```
Perhaps this can be improved by splitting --browser into a separate flag and option? Or dropping the argument? I'd create a PR but I don't know which approach @jonashaag would favour. As it stands, though, the feature is broken.

**Comment by jonashaag** [comment]
Oops. Didn't think of that... the clean approach is what you suggested. How about

```
-b --open-browser  open browser
-B --set-browser   set browser
```
or
```
-b --browser       open browser
-B --set-browser   set browser
```
or
```
-b --browser       open browser
-B --use-browser   set browser
```

Or something else? I'm happy to take your suggestions. What do you think would be a good solution?

**Comment by rjw57** [comment]
I think maybe the most idiomatic (English-wise) would be:

```
-b --browser       open browser
-B --with-browser   set browser
```

The the command line looks something like:

```console
$ klaus -b --with-browser foobar <repo>...
```

I'll open a PR with that and you can see what you think.
