### ISSUE TITLE
Windows 8.1 klaus

### ISSUE THREAD

**Issue by atrueresistance** [jonashaag/klaus#111]
I'm guessing this is a configuration problem on my part. I installed klaus, but am getting 

     'klaus' is not recognized as an internal or external command, operable program or batch file.

The environment variables seem correct. Am I missing a reference?

     C:\Python27;C:\Python27\Scripts;C:\Program Files (x86)\Git\cmd;

Klaus shows under C:\Python27\Scripts, but is registers as a file and not an application.

**Comment by Mechazawa** [comment]
Running Python under windows is always a recipe for disaster but it should be possible. 

 - Make sure the Python bin directory is in your path
 - Install the klaus dependencies (see bottom of post) using [pip](http://stackoverflow.com/questions/4750806/how-to-install-pip-on-windows)
  - `pip install flask pygments dulwich httpauth humanize`
 - `setup.py install`
 - Make sure the place where klaus gets installed is in your path
 - `klaus -h`

That *should* do the trick. I don't have access to a windows machine at the moment to test it but that should work. Working from old memories atm,

**Comment by atrueresistance** [comment]
Guess I have to be difficult running windows, here is the progress I have so far. 

pip freeze shows it's installed with dependencies. Python is installed in `C:\Python27`

    dulwich==0.9.8
    Flask==0.10.1
    httpauth==0.2
    humanize==0.5.1
    Pygments==2.0.2
    klaus==0.4.8

![Image of Scripts](http://i.imgur.com/PC98a7V.png)

    C:\Python27\Scripts>python klaus
    Traceback (most recent call last):
      File "klaus", line 4, in <module>
        __import__('pkg_resources').run_script('klaus==0.4.8', 'klaus')
      File "build\bdist.win-amd64\egg\pkg_resources\__init__.py", line 696, in run_s
    cript
      File "build\bdist.win-amd64\egg\pkg_resources\__init__.py", line 1614, in run_
    script
      File "c:\python27\lib\site-packages\klaus-0.4.8-py2.7.egg\EGG-INFO\scripts\kla
    us", line 12, in <module>
        from klaus import make_app
      File "C:\Python27\Scripts\klaus.py", line 4, in <module>
      File "build\bdist.win-amd64\egg\pkg_resources\__init__.py", line 696, in run_s
    cript
      File "build\bdist.win-amd64\egg\pkg_resources\__init__.py", line 1614, in run_
    script
      File "c:\python27\lib\site-packages\klaus-0.4.8-py2.7.egg\EGG-INFO\scripts\kla
    us", line 12, in <module>
        from klaus import make_app
    ImportError: cannot import name make_app

**Comment by jonashaag** [comment]
There should be no `klaus.pyc` file in that folder, how did it get there?

Btw, better ask such questions on the mailing list next time.

**Comment by Mechazawa** [comment]
> There should be no klaus.pyc file in that folder, how did it get there?

~python for windows~

Try running just `klaus`. Not `python klaus`.

**Comment by atrueresistance** [comment]
no go

**Comment by jonashaag** [comment]
No response from original reporter, closing.
