### ISSUE TITLE
Notice: Klaus is incorporating GPL code from dulwich

### ISSUE THREAD

**Issue by tony** [jonashaag/klaus#118]
klaus may not be able to claim this is ISC licensed, using dulwich which is GPLv2, a derivative is triggered.

https://github.com/jelmer/dulwich/blob/master/COPYING

See https://github.com/jelmer/dulwich/issues/153.

(I notice you are switching over via https://github.com/jonashaag/klaus/issues/96.)

**Comment by jelmer** [comment]
Dulwich has been relicensed; it is now dual Apache version 2.0 / GPL version 2 or later.

**Comment by tony** [comment]
@jelmer thank you!

**Comment by tony** [comment]
glad that worked out

**Comment by jonashaag** [comment]
Cool! Finally!
