### ISSUE TITLE
displaying description in list of repositories

### ISSUE THREAD

**Issue by jelmer** [jonashaag/klaus#119]
It would be great if klaus displayed the repository description in the list of repositories, i.e. http://klausdemo.lophus.org/

**Comment by posativ** [comment]
The demo doesn't have a description set, but it works (see [my instance](https://posativ.org/git)) with, e.g.

```text
~> ssh git@posativ.org desc isso
A commenting server similar to Disqus
```

**Comment by jelmer** [comment]
On Sat, Jun 13, 2015 at 06:17:50AM -0700, Martin Zimmermann wrote:
> The demo doesn't have a description set, but it works (see [my instance](https://posativ.org/git)) with, e.g.
> 
> ```text
> ~> ssh git@posativ.org desc isso
> A commenting server similar to Disqus
> ```

Sorry, you're right. I was just going from the demo.

Jelmer
