### ISSUE TITLE
integrate HTTP smart server

### ISSUE THREAD

**Issue by jelmer** [jonashaag/klaus#120]
It would be nice if klaus supported serving repositories from its URLs, like cgit. In other words, if this worked:

$ git clone http://klausdemo.lophus.org/nginx/

It should be easy to hook this up with dulwich.web.

**Comment by posativ** [comment]
This is already implemented.

**Comment by jelmer** [comment]
On Sat, Jun 13, 2015 at 06:18:47AM -0700, Martin Zimmermann wrote:
> This is already implemented.
If it is, it doesn't appear to be working for me - at least not for
the demo.

Jelmer

**Comment by posativ** [comment]
It isn't enabled by default, I think: https://github.com/jonashaag/klaus/wiki/Smart-HTTP

**Comment by jelmer** [comment]
On Sat, Jun 13, 2015 at 10:11:53AM -0700, Martin Zimmermann wrote:
> It isn't enabled by default, I think: https://github.com/jonashaag/klaus/wiki/Smart-HTTP

Ah, cool. I'll give that a try.

**Comment by jonashaag** [comment]
This should work. If it doesn't please open a bug report.
