### ISSUE TITLE
Display clone URL

### ISSUE THREAD

**Issue by jelmer** [jonashaag/klaus#122]
It would be great if klaus could display clone instructions for each repository, if known.

If the smart server is enabled, it could display the URL for that. In other situations, it could retrieve one from the repository config.

**Comment by jonashaag** [comment]
This is already implemented for Smart HTTP. Where exactly do you get the URL from in the other case?

**Comment by jelmer** [comment]
On Thu, Jun 25, 2015 at 12:49:36AM -0700, Jonas Haag wrote:
> This is already implemented for Smart HTTP. Where exactly do you get the URL from in the other case?
I was thinking either a setting for the public URL in the git config file, or
alternatively some sort of translation setting in the klaus config. I.e.:

PUBLIC_URL = lambda r: r.replace("/srv/git/", "git://jelmer.uk/")

Jelmer

**Comment by jonashaag** [comment]
I think we could support `.git/cloneurl` file, `gitweb.url` and `@git_base_url_list` options. The relationship of these options has to be explained to me in simple English as I couldn't figure it out.
