### ISSUE TITLE
No module named `dulwich.errors`

### ISSUE THREAD

**Issue by matthiasbeyer** [jonashaag/klaus#129]
Hi,

I'm packaging klaus for nixos, as you can see [here](https://github.com/NixOS/nixpkgs/pull/8526). I get the following error when starting klaus:

```
$ klaus /some/repo/
Traceback (most recent call last):
  File "/nix/store/qvhw5wp0yp22zacrvnj66hxdpvzin0h2-python2.7-klaus-0.4.9/bin/.klaus-wrapped", line 10, in <module>
    from dulwich.errors import NotGitRepository
ImportError: No module named dulwich.errors
```

As you're propably not a nixos guy:

* dulwich is in version 0.1.10a

**Comment by jonashaag** [comment]
See `setup.py`: dulwich>=0.9.6 is required.

**Comment by matthiasbeyer** [comment]
Ah, my fault: I meant `dulwich-0.10.1a` is available, not `0.1.10a`.

**Comment by jonashaag** [comment]
Maybe the dependencies aren't installed correctly.

**Comment by matthiasbeyer** [comment]
It seems like an packaging error, yes. Anyways, thanks for your quick reply!
