### ISSUE TITLE
Deployment via CGI

### ISSUE THREAD

**Issue by artur-scholz** [jonashaag/klaus#151]
Great work you did! I tried the standalone server, which is just fine.
However, I only have CGI available to integrate with Apache server. I tried the following CGI script:

```
#!/usr/bin/env python

TITLE = u"My site title"
REPOSITORIES = ["/home/webserver/tools/test",]

from wsgiref.handlers import CGIHandler
from klaus import make_app

app = make_app(REPOSITORIES, TITLE)
CGIHandler().run(app)
```

It seems to work partially, but without any style formatting and links are broken as well.

Any ideas?

**Comment by jonashaag** [comment]
Please bring this to the mailing list or gitter. My gut reaction is: Why would anyone, ever, want to use CGI in 2016?
