### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by gschwepp** [jonashaag/klaus#153]
Hi,
I am running klaus via uwsgi in a FreeBSD (10.2) jail serving klaus via unix socket to my nginx webserver. I added some new repositories and they are displayed correctly in the repo overview. When I try to enter a repo uwsgi throws  "500 Internal Server Error".  There is no error in the logs or something like that. In my uwsgi log it only says: 

"[pid: 6919|app: 0|req: 14/32]  [IP]  () {44 vars in 732 bytes} [Wed Mar  9 13:16:42 2016] GET /test/ => generated 291 bytes in 19 msecs (HTTP/1.1 500) 2 headers in 84 bytes (1 switches on core 0)"

This seems to be more or less the same issue as described here: https://groups.google.com/forum/#!topic/klaus-users/ThXJ09sptZ8

Any ideas how i can track down the problem? 

Cheers

**Comment by jonashaag** [comment]
Hm, uWSGI should just log this to stderr, but if it doesn't, you can start the `bin/klaus` development server using `--debug` and use that as nginx's target

**Comment by gschwepp** [comment]
Hi, 

with `klaus --host 10.1.1.13 --debug /usr/home/git/private/klaus_test`. I configured my nginx to target 10.1.1.13:8080. When I try to load website I get the following error: 

>  ----------------------------------------
> Exception happened during processing of request from ('10.1.1.10', 44704)
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
>     self.process_request(request, client_address)
>   File "/usr/local/lib/python2.7/SocketServer.py", line 321, in process_request
>     self.finish_request(request, client_address)
>   File "/usr/local/lib/python2.7/SocketServer.py", line 334, in finish_request
>     self.RequestHandlerClass(request, client_address, self)
>   File "/usr/local/lib/python2.7/SocketServer.py", line 655, in __init__
>     self.handle()
>   File "/usr/local/lib/python2.7/site-packages/werkzeug/serving.py", line 216, in handle
>     rv = BaseHTTPRequestHandler.handle(self)
>   File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 340, in handle
>     self.handle_one_request()
>   File "/usr/local/lib/python2.7/site-packages/werkzeug/serving.py", line 250, in handle_one_request
>     elif self.parse_request():
>   File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 286, in parse_request
>     self.send_error(400, "Bad request syntax (%r)" % requestline)
>   File "/usr/local/lib/python2.7/BaseHTTPServer.py", line 364, in send_error
>     self.log_error("code %d, message %s", code, message)
>   File "/usr/local/lib/python2.7/site-packages/werkzeug/serving.py", line 272, in log_error
>     self.log('error', *args)
>   File "/usr/local/lib/python2.7/site-packages/werkzeug/serving.py", line 278, in log
>     _log(type, '%s - - [%s] %s\n' % (self.address_string(),
>   File "/usr/local/lib/python2.7/site-packages/werkzeug/serving.py", line 266, in address_string
>     return self.environ['REMOTE_ADDR']
> AttributeError: 'WSGIRequestHandler' object has no attribute 'environ'
> ----------------------------------------

For me this looks like a completly different problem. Can I start klaus in debugging mode using from my rc.conf?

**Comment by jonashaag** [comment]
> Can I start klaus in debugging mode using from my rc.conf?

It should always print a traceback, no command line switch needed. Try the command line without `--debug`, this should print the traceback to stderr.

**Comment by gschwepp** [comment]
I get the same error message without `--debug`.

**Comment by jonashaag** [comment]
This seems to be a bug in Werkzeug, one of the libraries klaus is based on: mitsuhiko/werkzeug#832

It only happens when using the built-in web server. So there are multiple steps you could take:

* Fix uWSIG not reporting error
* Revert Werkzeug to `<0.11` (where the bug has been introduced)
* Replace Werkzeug temporarily with a fixed version: https://github.com/nathancahill/werkzeug/archive/fix-missing-environ.zip
* Use another WSGI server for testing, like Python's built-in `wsgiref`.

**Comment by gschwepp** [comment]
It is a strange error in my system. When I start uwsgi manually on command line everything works fine, but when I use my rc. configuration it does not. So this can be closed. 

Thank you.
