### ISSUE TITLE
Honour SCRIPT_NAME if HTTP_X_SCRIPT_NAME isn't set

### ISSUE THREAD

**Issue by sbraz** [jonashaag/klaus#155]
I spent quite a while understanding how to make klaus work behind a reverse proxy in a location that is not `/`.
Following [the uwsgi doc](http://uwsgi-docs.readthedocs.org/en/latest/Nginx.html#hosting-multiple-apps-in-the-same-process-aka-managing-script-name-and-path-info) (using `--mount` and `--manage-script-name`) should have worked but it did not because `SCRIPT_NAME` is overwritten [here](https://github.com/jonashaag/klaus/commit/6a93db943a189f0927c3964bd8d7efbdac25e2d9#diff-b0d32d447cbf764ad4e5b70017ded586R56).
Could you change the function so that `SCRIPT_NAME` is not altered if `HTTP_X_SCRIPT_NAME` isn't set?

**Comment by jonashaag** [comment]
Oops, yeah, agreed.

**Comment by sbraz** [comment]
Do you think you'll do it or do you want me to make a PR?

**Comment by jonashaag** [comment]
Probably not today, so feel free to PR
