### ISSUE TITLE
Add an example nginx/uwsgi configuration to the Wiki

### ISSUE THREAD

**Issue by sbraz** [jonashaag/klaus#156]
Depending on the outcome of https://github.com/jonashaag/klaus/issues/155, the configuration would be different. At the moment, the following works:
```nginx
location /klaus/ {
  uwsgi_param HTTP_X_SCRIPT_NAME /klaus;
  # alternatively, uwsgi's --mount /klaus=/path/to/app.wsgi may be used
  rewrite /klaus(/.*) $1 break;
  include uwsgi_params;
  uwsgi_pass unix:/path/to/uwsgi.sock;
}
```
And uwsgi can be run with `uwsgi --plugin python27 --socket /path/to/uwsgi.sock --wsgi-file /path/to/app.wsgi`.

**Comment by sbraz** [comment]
When `SCRIPT_NAME` is properly handled, we will only need:
```nginx
location /klaus/ {
  include uwsgi_params;
  uwsgi_pass unix:/path/to/uwsgi.sock;
}
```
And `uwsgi --plugin python27 --socket /path/to/uwsgi.sock --mount /klaus=/path/to/app.wsgi`

Also, isn't the bit about importing `ProxyFix` outdated? klaus does it by itself, right?

**Comment by jonashaag** [comment]
See also #25, I'm not really up-to-date with respect to the `uwsgi_modifier 30` thing.

> Also, isn't the bit about importing ProxyFix outdated? klaus does it by itself, right?

If you're talking about the "klaus behind reverse proxy" wiki page, then I'd say yes it's outdated because it is already present in your WSGI chain if you use `make_app`. Feel free to change the page accordingly.

**Comment by sbraz** [comment]
Oh, you're right, it's a Wiki that I can edit :smile: 
The `uwsgi_modifier 30` part is not required if `--mount` is used. I'll wait for you to fix the `SCRIPT_NAME` thing and I'll update the Wiki accordingly.

**Comment by jonashaag** [comment]
> The uwsgi_modifier 30 part is not required if --mount is used.

What does this https://github.com/unbit/uwsgi/issues/935 say then? I don't really understand what's being discussed there, not enough experience with uwsgi

**Comment by sbraz** [comment]
I don't really understand what the reporter is trying to achieve either (probably something more complex than proxifying an app).
I just tried commenting the line that forces `SCRIPT_NAME` and I can confirm that my config from https://github.com/jonashaag/klaus/issues/156#issuecomment-209300213 works so I don't think we need to worry about this modifier thing.

**Comment by jonashaag** [comment]
OK, sounds good to me.

**Comment by jonashaag** [comment]
I added some words there https://github.com/jonashaag/klaus/wiki/Klaus-behind-a-reverse-proxy

Mind a quick review?

**Comment by sbraz** [comment]
I checked and `--manage-script-name` is required for `--mount` to work as expected. If `--mount` isn't used, `--wsgi-file` must be included.
I updated the wiki accordingly. I'll let you close the issue if it's all good :)
Will you make a new release with the `SCRIPT_NAME` fix?

**Comment by jonashaag** [comment]
LGTM, thx!
