### ISSUE TITLE
Using htdigest file in wsgi_autoreload.py results in "I/O operation on closed file"

### ISSUE THREAD

**Issue by jimmyppi** [jonashaag/klaus#169]
The htdigest file is opened like this in [wsgi_autoreload.py](https://github.com/jonashaag/klaus/blob/master/klaus/contrib/wsgi_autoreload.py)

    with open(os.environ['KLAUS_HTDIGEST_FILE']) as file:
        application = make_autoreloading_app(
            os.environ.get('KLAUS_REPOS_ROOT') or os.environ['KLAUS_REPOS'],
            os.environ['KLAUS_SITE_NAME'],
            os.environ.get('KLAUS_USE_SMARTHTTP'),
            file)

But `make_autoreloading_app` returns an inner function that does not call `klaus.make_app` until `application` is called. At that moment we are outside of the with statement and the file object has been closed:

```
def make_autoreloading_app(repos_root, *args, **kwargs):
    def app(environ, start_response):
        if _.should_reload:
            # Refresh inner application with new repo list
            print("Reloading repository list...")
            _.inner_app = make_app(
                [os.path.join(repos_root, x) for x in os.listdir(repos_root)],
                *args, **kwargs
            )
            _.should_reload = False
        return _.inner_app(environ, start_response)

    # Background thread that polls the directory for changes
    poller_thread = threading.Thread(target=(lambda: poll_for_changes(10, repos_root)))
    poller_thread.daemon = True
    poller_thread.start()

    return app
```

I could make a fix for this, and would also like to expose more kwargs as environment variables.

**Comment by jonashaag** [comment]
Thanks for the report. That definitely looks like a bug to me. I'm interested to see what your suggested fix is.

I'm also OK with exposing more kwargs but I'd be thankful if you could put that in another pull request, if possible.

**Comment by jimmyppi** [comment]
I would like to skip `*args` in `make_autoreloading_app` so that we know that `htdigest_file`, if given, is in `kwargs`:

    def make_autoreloading_app(repos_root, site_name, **kwargs):

And then open the file when calling `make_app`:

    repo_paths = [os.path.join(repos_root, x) for x in os.listdir(repos_root)]
    if 'htdigest_file' in kwargs:
            with open(kwargs['htdigest_file']) as htdigest_file:
                kwargs['htdigest_file'] = htdigest_file
                _.inner_app = make_app(repo_paths, site_name, **kwargs)
    else:
        _.inner_app = make_app(repo_paths, site_name, **kwargs)

Yes, separate pull requests sounds good.

**Comment by jonashaag** [comment]
I think it's better to keep input/configuration out of the main WSGI/app code. How about one of the following

- Allow both file-like objects and strings in `httpauth`
- Read the contents into a `TextIO` (or whatever) object and pass that to the WSGI app

**Comment by jimmyppi** [comment]
Yes, I think I would prefer the TextIO option, I don't like that an argument can be of several different types. It would then become something like:

```
if 'KLAUS_HTDIGEST_FILE' in os.environ:
    with open(os.environ['KLAUS_HTDIGEST_FILE'], 'r') as htdigest_file:
        htdigest_io = TextIO(htdigest_file.read())
    application = make_autoreloading_app(
        os.environ.get('KLAUS_REPOS_ROOT') or os.environ['KLAUS_REPOS'],
        os.environ['KLAUS_SITE_NAME'],
        os.environ.get('KLAUS_USE_SMARTHTTP'),
        htdigest_io,
    )
```

**Comment by jonashaag** [comment]
:+1: if you could leave a comment there as to why we "buffer" the file there that would be great!
