### ISSUE TITLE
relative links in README.md on index page link to incorrect page

### ISSUE THREAD

**Issue by jelmer** [jonashaag/klaus#177]
Links on the index page link to pages under the project root, rather than to actual files.

E.g. "DAV compliance" on https://jelmer.uk/code/xandikos/ links to https://jelmer.uk/code/xandikos/notes/dav-compliance.md, while the correct target should be https://jelmer.uk/code/xandikos/blob/master/notes/dav-compliance.md

(https://jelmer.uk/code/xandikos/blob/master/README.md has correct relative links)

(Sorry, this is a bug that I introduced when I added the index pages..)

Is there an easy way to add a relative base to links in markdown pages?

**Comment by jonashaag** [comment]
Oh, never thought about that to be honest. So it's not actually a bug you introduced.

I guess we can just copy whatever GitHub, GitLab, Gogs, etc. do.

It's also not a problem specific to Markdown.
