### ISSUE TITLE
switching pages of commit history is broken

### ISSUE THREAD

**Issue by jahir** [jonashaag/klaus#192]
clicking on one of the little "»»" buttons of the commit history results in a 404 Not Found with the page saying "No such commit u'tree/master/'". This is unrelated to my setup, since the demo on http://klausdemo.lophus.org/klaus/ behaves the same. The broken link there is http://klausdemo.lophus.org/klaus/tree/master/?page=1

**Comment by jonashaag** [comment]
Looks like a duplicate of https://github.com/jonashaag/klaus/issues/190, could you try with the latest master?

**Comment by jahir** [comment]
The cause seems to be same as in #190, it works if I manually edit the URL to `.../master?page=1`.

I had a hard time finding a way to install the master head and was a little embarrassed that is just a simple `pip install --upgrade git+https://github.com/jonashaag/klaus.git`, maybe you could add that to one of your pages.

So it works indeed with head, so this issue can be closed.
