### ISSUE TITLE
Setup with Gunicorn and Daemontools

### ISSUE THREAD

**Issue by FriedrichFroebel** [jonashaag/klaus#193]
I am currently trying to set `klaus` up using [Gunicorn](http://gunicorn.org/) with [daemontools](https://cr.yp.to/daemontools.html) on an Apache server, but I keep getting errors using a similar configuration as for a "normal" `flask` application.

Normally, I would start a flask application like this inside my `~/service/run` file:

```bash
exec /home/me/bin/gunicorn --error-logfile - --reload --chdir /home/me/flaskA/ --bind 127.0.0.1:12345 wsgi:app 2>&1
```

Using a similar syntax for `klaus` (`exec /home/me/bin/gunicorn --error-logfile - --reload --env KLAUS_SITE_NAME="Klaus Test" --env KLAUS_REPOS="/home/me/klaus/" --chdir /home/me/klaus/klaus/contrib/ --bind 127.0.0.1:12346 wsgi 2>&1`) fails. I get a 503 HTML error and an error message inside my error log:

> Connection refused: proxy: HTTP: attempt to connect to 127.0.0.1:12346 (*) failed

The same problem occurs when using the example from the README (`klaus` is installed via `pip`).

My `.htaccess` file:

```apache
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteBase /
RewriteRule ^(.*)$ http://127.0.0.1:12346/$1 [P]
RequestHeader set X-Forwarded-Proto https env=HTTPS
```

Is there a way to fix this?

**Comment by jonashaag** [comment]
Very difficult to say what's wrong here without having all of the logs. Could you paste any logs you can find that may contain relevant information (Apache, Gunicorn, Daemontools, more?). Also be sure to enable verbose output everywhere. Please also try if it works outside the Daemontools environment, and outside the Apache environment (so, Gunicorn-only). Also, does the `klaus` binary work for you?

**Comment by FriedrichFroebel** [comment]
Moving the `klaus` application to a new `daemontools` service produces the following output inside my log file:

```
[INFO] Starting gunicorn 19.7.1
[INFO] Listening at: http://127.0.0.1:12346 (12298)
[INFO] Using worker: sync
[INFO] Booting worker with pid: 12349
[ERROR] Exception in worker process
Traceback (most recent call last):
   File "/home/me/lib/python2.6/gunicorn/arbiter.py", line 578, in spawn_worker
     worker.init_process()
   File "/home/me/lib/python2.6/gunicorn/workers/base.py", line 126, in init_process
     self.load_wsgi()
   File "/home/me/lib/python2.6/gunicorn/workers/base.py", line 135, in load_wsgi
     self.wsgi = self.app.wsgi()
   File "/home/me/lib/python2.6/gunicorn/app/base.py", line 67, in wsgi
     self.callable = self.load()
   File "/home/me/lib/python2.6/gunicorn/app/wsgiapp.py", line 65, in load
     return self.load_wsgiapp()
   File "/home/me/lib/python2.6/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
     return util.import_app(self.app_uri)
   File "/home/me/lib/python2.6/gunicorn/util.py", line 352, in import_app
     __import__(module)
   File "/home/me/klaus/klaus/__init__.py", line 5, in <module>
     from klaus import views, utils
   File "/home/me/klaus/klaus/views.py", line 25, in <module>
     from klaus.highlighting import highlight_or_render
   File "/home/me/klaus/klaus/highlighting.py", line 17, in <module>
     PYGMENTS_CTAGS_LANGUAGE_MAP = dict((get_lexer_by_name(l).name, l) for l in CTAGS_SUPPORTED_LANGUAGES)
   File "/home/me/klaus/klaus/highlighting.py", line 17, in <genexpr>
     PYGMENTS_CTAGS_LANGUAGE_MAP = dict((get_lexer_by_name(l).name, l) for l in CTAGS_SUPPORTED_LANGUAGES)
   File "/usr/lib/python2.6/site-packages/pygments/lexers/__init__.py", line 84, in get_lexer_by_name
     raise ClassNotFound('no lexer for alias %r found' % _alias)
 ClassNotFound: no lexer for alias 'Asm' found
[INFO] Worker exiting (pid: 12349)
[INFO] Shutting down: Master
[INFO] Reason: Worker failed to boot.
```

**Comment by FriedrichFroebel** [comment]
Seems like it works now after updating my Python libraries and moving the application to a subdomain (using it not from a document root resulted in errors). I seems like the Markdown of the README file does not get rendered. How to resolve this?

**Comment by jonashaag** [comment]
Klaus does not support Python 2.6 anymore, please update to Python 2.7 or Python 3.x.

For markdown rendering, see https://github.com/jonashaag/klaus/wiki/Markup-rendering
