### ISSUE TITLE
Running inside a subdir

### ISSUE THREAD

**Issue by FriedrichFroebel** [jonashaag/klaus#197]
I am trying to run `klaus` from a subdirectory to be able to access it using `example.org/klaus/` for example. The index page gets displayed, but all the static files cannot be found as they are expected inside the `example.org/static/` directory (opening a repo does not work, too).

My `wsgi.py` file:

```python3
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

TITLE = "Klaus"
REPOSITORIES = [ "/home/me/klaus", ]

from klaus import make_app

application = make_app(REPOSITORIES, TITLE)
```

My `.htaccess` file (I am running `klaus` with `gunicorn`):

```apache
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteBase /
RewriteRule ^(.*)$ http://127.0.0.1:12345/$1 [P]
```

Is there a way to fix this?

**Comment by jonashaag** [comment]
Are you using ProxyFix correctly? https://github.com/jonashaag/klaus/blob/master/klaus/utils.py#L20

**Comment by FriedrichFroebel** [comment]
Do you have an example on how to use it? Seems like the `ProxyFix` class gets called inside the `make_app()` method, but where do I have to set the `X-Script-Name` value to get it passed?

**Comment by jonashaag** [comment]
In your reverse proxy (e.g. Apache)
