### ISSUE TITLE
Download tarballs checksum differently each download

### ISSUE THREAD

**Issue by BonkaBonka** [jonashaag/klaus#203]
If I download a tarball from a tag, and perform a checksum on it, it's different each time:
~~~
$ curl --silent http://example.lan/git/myrepo/tarball/0.0.1/ | sha256sum
32225ceedce2f9456e15461ec2130a337c352c030152387bc521dab12ef25812  -
$ curl --silent http://example.lan/git/myrepo/tarball/0.0.1/ | sha256sum
33fe4faedaffa15e37b7329ee013108e90623d0a0434a0fe8700243d12ead6da  -
~~~

This is breaking my package manifests since they expect the checksums to be static.  Probably date-related?

**Comment by jonashaag** [comment]
That's possible. I guess the right place to start looking is Dulwich's tar code.

**Comment by BonkaBonka** [comment]
Also, I don't know what it would take to have the files nested within a subdirectory like GitHub does - right now the tarballs root everything at the top.  (I could open this as a separate issue if you want me to.)

**Comment by jonashaag** [comment]
Please open a separate issue for that and explain your issue in a bit more detail.

I've found the issue to be a problem with the Python tar implementation: https://bugs.python.org/issue31526

However this is something we could work around in Dulwich/klaus.

**Comment by jelmer** [comment]
I can confirm that this is fixed after the change to dulwich.

**Comment by jonashaag** [comment]
Thanks for the feedback Jelmer
