### ISSUE TITLE
Image in a repository not served by klaus

### ISSUE THREAD

**Issue by simon-v** [jonashaag/klaus#218]
I am trying to create a mirror of https://github.com/simon-v/tridenticon/ on my own web server. One of the files in the repo is a tridenticon.png file which shows up in the file list, but returns a 404 when clicked or referenced in an href. All other files seem to be served correctly.

The image's URL is correctly set to "/blob/master/tridenticon.png".

The repository is a typical bare repository. It is served by Nginx with the options specified in the https://github.com/jonashaag/klaus/wiki/Klaus-behind-a-reverse-proxy#nginx-example page, and also a `try-files $uri $uri/ =404;` location directive.

Assistance in identifying the source of my difficulties would be most welcome. I can see that http://klausdemo.lophus.org/klaus/blob/master/klaus/static/favicon.png on the demo site is served just fine, so it may as well be some form of misconfiguration on my part.

**Comment by jonashaag** [comment]
Try the config option `error_log /your/log debug` in nginx

**Comment by simon-v** [comment]
Thank you! With your hint, i have successfully identified a slight Nginx configuration mistake that caused the trouble. For future reference by anyone who stumbles upon this thread, the solution is as follows:

You need to keep any hotlinking protection rules you might have _after_ the klaus location rules.

My apologies to the author! Klaus indeed _Just Works™._
