### ISSUE TITLE
Sort repositories by update date by default?

### ISSUE THREAD

**Issue by infertux** [jonashaag/klaus#222]
I think [this](https://github.com/jonashaag/klaus/blob/558a3cdacc3c3aef3dad5cf1596e19ae6203ef3d/klaus/views.py#L35) should be the default. It makes much more sense than sorting them alphabetically IMHO.

Although I guess the sorting method could be added as a global configuration setting (similarly to `KLAUS_USE_SMARTHTTP`) so people could configure it as they wish.

Thoughts?

**Comment by jonashaag** [comment]
Let’s make it by last update by default. PR welcome

**Comment by infertux** [comment]
FYI I gave it a try [there](https://github.com/jonashaag/klaus/compare/master...infertux:sort-by) but this feels very inelegant to me. Moreover, I'm getting a bunch of `OSError: [Errno 98] Address already in use` errors when I run `./runtests.sh` on my machine so I'll wait for an actual Python dev to do it properly :stuck_out_tongue_closed_eyes: Feel free to close the issue.

**Comment by s-ol** [comment]
This seems to be the case now, so this issue can be closed.

> Moreover, I'm getting a bunch of OSError: [Errno 98] Address already in use errors when I run ./runtests.sh on my machine so I'll wait for an actual Python dev to do it properly

I also had this issue, for me invoking them as

    CI=1 ./runtests.sh

This adds a 1s delay between tests, slowing them down, but it gets you useful results :slightly_smiling_face:

**Comment by jonashaag** [comment]
Thanks for the feedback. Maybe we should just make the sleep the default.
