### ISSUE TITLE
Error in URL for files / commits with Python3

### ISSUE THREAD

**Issue by lcheylus** [jonashaag/klaus#233]
I installed Klaus from sources on Linux Debian server (distrib stable/stretch), Python3 version 3.5.3.

When I browse repositories (served through klaus script or via UWSGI + Nginx server), URL for files (in treeview) and commits (in history) are incorrect : URL are prefixed with flag 'b' (bytes) => error 404.

```
<SITE>/<REPO>/blob/master/b'<filename>'
<SITE>/<REPO>/commit/b'<hash>'/
```

If I suppressed the 'b' flag in URL, access to files / commit is valid.

Same error on Linux Debian testing with Python3 version 3.7.3.
With Python2 version 2.7.16, URL for files and commits are correct (no flag for bytes).

**Comment by jonashaag** [comment]
Can you provide a test repo that demonstrates the issue?

**Comment by kinverarity1** [comment]
I also have this issue on Windows 10 64-bit, with Python 3.7.3 64-bit.

Installed packages: dulwich-0.19.11 urllib3-1.24.1 Werkzeug-0.15.2 flask-1.0.2 httpauth-0.3 humanize-0.5.1 itsdangerous-1.1.0 klaus-1.3.0

Then used the ``klaus`` script on a local clone of this repo: https://github.com/kinverarity1/lasio. Same error as above. The final part of the URLs have the prefix ``b'`` and the suffix ``'``.

I tested on the same machine using a Python 2.7.16 environment (installed versions of packages dulwich-0.19.11 urllib3-1.24.1 Jinja2-2.10.1 MarkupSafe-1.1.1 Werkzeug-0.15.2 click-7.0 flask-1.0.2 httpauth-0.3 humanize-0.5.1 itsdangerous-1.1.0 klaus-1.3.0 pygments-2.3.1 six-1.12.0) and run the klaus script on the same repo, and it worked fine.

Is Python 3 supported? (thanks for the package by the way!)

**Comment by jonashaag** [comment]
Could you guys test this fix: https://github.com/jonashaag/klaus/pull/234

**Comment by kinverarity1** [comment]
Thank you, the problem does not appear with #234 on both Python 2.7 and 3.7 for me.

**Comment by lcheylus** [comment]
No sorry, this fix is incomplete :(

I tested it with Python 3.7.3 on Debian Linux testing with Klaus repository (git clone from GitHub)
`klaus --host IP --port 8080 ~/dev/klaus.git/`

- paths are correct for GIT history
- paths are correct for RAW diff of a commit
- paths are not correct in a directory for treeview

For example, for `dumbtest.py` file in `tools` directory, path is `http://HOST:PORT//klaus/blob/master/dumbtest.py` => error 404 instead of `http://HOST:PORT//klaus/blob/master/tools/dumbtest.py`

**Comment by jonashaag** [comment]
I'm offline for a few days, if someone wants to this fix on their own feel free to send a PR.

**Comment by jonashaag** [comment]
Please try now

**Comment by lcheylus** [comment]
I tested Klaus last version v1.4 with Python 3.7 : everything is OK. Thanks for the fix.
