### ISSUE TITLE
git init --bare,  or just git init ...

### ISSUE THREAD

**Issue by stappersg** [jonashaag/klaus#251]
Hi,

Here someone who is starting with `klaus`.

I'm about to find out if _bare_ git repositories can be displayed with `klaus`.

Current documentation doesn't tell, but IMO it should tell.

**Comment by jonashaag** [comment]
It can. Feel free to add it to the docs somewhere!

**Comment by stappersg** [comment]
On Fri, Jun 19, 2020 at 06:06:57AM -0700, Jonas Haag wrote:
> It can. Feel free to add it to the docs somewhere!

Acknowledge.

**Comment by stappersg** [comment]
I did forgot about this.
It was working on https://git.inept.dev/~doyle/rgit.git/about
that did bring be back here. To close this issue.
