### ISSUE TITLE
Syntax error from  klaus --help

### ISSUE THREAD

**Issue by stappersg** [jonashaag/klaus#252]
Hi,

For me results `klaus --help` in a syntax error, not showing a help text.
This happens on a fresh Debian system after `ansible pip install klaus`.
To rule out _Ansible_  was a local  `pip uninstall klaus` done.

An reinstall with  some version information:
```
root@hamada:~# cat /etc/debian_version 
10.4
root@hamada:~# klaus --help
-bash: klaus: command not found
root@hamada:~# pip --version
pip 18.1 from /usr/lib/python2.7/dist-packages/pip (python 2.7)
root@hamada:~# python --version
Python 2.7.16
root@hamada:~# pip install klaus
Collecting klaus
Requirement already satisfied: pygments in /usr/local/lib/python2.7/dist-packages (from klaus) (2.5.2)
Requirement already satisfied: httpauth in /usr/local/lib/python2.7/dist-packages (from klaus) (0.3)
Requirement already satisfied: humanize in /usr/local/lib/python2.7/dist-packages (from klaus) (1.0.0)
Requirement already satisfied: six in /usr/lib/python2.7/dist-packages (from klaus) (1.12.0)
Requirement already satisfied: Werkzeug>=0.15.0 in /usr/local/lib/python2.7/dist-packages (from klaus) (1.0.1)
Requirement already satisfied: flask in /usr/local/lib/python2.7/dist-packages (from klaus) (1.1.2)
Requirement already satisfied: dulwich>=0.19.3 in /usr/local/lib/python2.7/dist-packages (from klaus) (0.20.2)
Requirement already satisfied: Jinja2>=2.10.1 in /usr/local/lib/python2.7/dist-packages (from flask->klaus) (2.11.2)
Requirement already satisfied: itsdangerous>=0.24 in /usr/local/lib/python2.7/dist-packages (from flask->klaus) (1.1.0)
Requirement already satisfied: click>=5.1 in /usr/local/lib/python2.7/dist-packages (from flask->klaus) (7.1.2)
Requirement already satisfied: urllib3>=1.24.1 in /usr/local/lib/python2.7/dist-packages (from dulwich>=0.19.3->klaus) (1.25.9)
Requirement already satisfied: certifi in /usr/local/lib/python2.7/dist-packages (from dulwich>=0.19.3->klaus) (2020.4.5.2)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python2.7/dist-packages (from Jinja2>=2.10.1->flask->klaus) (1.1.1)
Installing collected packages: klaus
Successfully installed klaus-1.5.2
root@hamada:~# klaus --help
Traceback (most recent call last):
  File "/usr/local/bin/klaus", line 11, in <module>
    from dulwich.repo import Repo
  File "/usr/local/lib/python2.7/dist-packages/dulwich/repo.py", line 51, in <module>
    from dulwich.object_store import (
  File "/usr/local/lib/python2.7/dist-packages/dulwich/object_store.py", line 31, in <module>
    from dulwich.diff_tree import (
  File "/usr/local/lib/python2.7/dist-packages/dulwich/diff_tree.py", line 32, in <module>
    from dulwich.objects import (
  File "/usr/local/lib/python2.7/dist-packages/dulwich/objects.py", line 154
    def object_header(num_type: int, length: int) -> bytes:
                              ^
SyntaxError: invalid syntax
root@hamada:~# 
```

How to overcome that synatx error?

**Comment by jonashaag** [comment]
Maybe Dulwich has no Python 2 support anymore.

Python 2 is deprecated. Switch to Python 3.

**Comment by jelmer** [comment]
Hoi Geert!

On Sat, Jun 20, 2020 at 05:55:34AM -0700, Geert Stappers wrote:
> For me results `klaus --help` in a syntax error, not showing a help text.
> This happens on a fresh Debian system after `ansible pip install klaus`.
> To rule out _Ansible_  was a local  `pip uninstall klaus` done.
> 
> An reinstall with  some version information:
> ```
> root@hamada:~# cat /etc/debian_version 
> 10.4
> root@hamada:~# klaus --help
> -bash: klaus: command not found
> root@hamada:~# pip --version
> pip 18.1 from /usr/lib/python2.7/dist-packages/pip (python 2.7)
> root@hamada:~# python --version
> Python 2.7.16
> root@hamada:~# pip install klaus
> Collecting klaus
> Requirement already satisfied: pygments in /usr/local/lib/python2.7/dist-packages (from klaus) (2.5.2)
> Requirement already satisfied: httpauth in /usr/local/lib/python2.7/dist-packages (from klaus) (0.3)
> Requirement already satisfied: humanize in /usr/local/lib/python2.7/dist-packages (from klaus) (1.0.0)
> Requirement already satisfied: six in /usr/lib/python2.7/dist-packages (from klaus) (1.12.0)
> Requirement already satisfied: Werkzeug>=0.15.0 in /usr/local/lib/python2.7/dist-packages (from klaus) (1.0.1)
> Requirement already satisfied: flask in /usr/local/lib/python2.7/dist-packages (from klaus) (1.1.2)
> Requirement already satisfied: dulwich>=0.19.3 in /usr/local/lib/python2.7/dist-packages (from klaus) (0.20.2)
> Requirement already satisfied: Jinja2>=2.10.1 in /usr/local/lib/python2.7/dist-packages (from flask->klaus) (2.11.2)
> Requirement already satisfied: itsdangerous>=0.24 in /usr/local/lib/python2.7/dist-packages (from flask->klaus) (1.1.0)
> Requirement already satisfied: click>=5.1 in /usr/local/lib/python2.7/dist-packages (from flask->klaus) (7.1.2)
> Requirement already satisfied: urllib3>=1.24.1 in /usr/local/lib/python2.7/dist-packages (from dulwich>=0.19.3->klaus) (1.25.9)
> Requirement already satisfied: certifi in /usr/local/lib/python2.7/dist-packages (from dulwich>=0.19.3->klaus) (2020.4.5.2)
> Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python2.7/dist-packages (from Jinja2>=2.10.1->flask->klaus) (1.1.1)
> Installing collected packages: klaus
> Successfully installed klaus-1.5.2
> root@hamada:~# klaus --help
> Traceback (most recent call last):
>   File "/usr/local/bin/klaus", line 11, in <module>
>     from dulwich.repo import Repo
>   File "/usr/local/lib/python2.7/dist-packages/dulwich/repo.py", line 51, in <module>
>     from dulwich.object_store import (
>   File "/usr/local/lib/python2.7/dist-packages/dulwich/object_store.py", line 31, in <module>
>     from dulwich.diff_tree import (
>   File "/usr/local/lib/python2.7/dist-packages/dulwich/diff_tree.py", line 32, in <module>
>     from dulwich.objects import (
>   File "/usr/local/lib/python2.7/dist-packages/dulwich/objects.py", line 154
>     def object_header(num_type: int, length: int) -> bytes:
>                               ^
> SyntaxError: invalid syntax
> root@hamada:~# 
> ```
> 
> How to overcome that synatx error?
Dulwich only supports python3 nowadays; you can either install the
python3 version of klaus ("pip3 install klaus" on Debian) or force an
older version of Dulwich (prior to 0.20).

Cheers,

Jelmer

**Comment by stappersg** [comment]
LOL
meanwhile I got
```
$ python
Python 2.7.16 (default, Oct 10 2019, 22:02:15) 
[GCC 8.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from dulwich.repo import Repo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/dulwich/repo.py", line 51, in <module>
    from dulwich.object_store import (
  File "/usr/local/lib/python2.7/dist-packages/dulwich/object_store.py", line 31, in <module>
    from dulwich.diff_tree import (
  File "/usr/local/lib/python2.7/dist-packages/dulwich/diff_tree.py", line 32, in <module>
    from dulwich.objects import (
  File "/usr/local/lib/python2.7/dist-packages/dulwich/objects.py", line 154
    def object_header(num_type: int, length: int) -> bytes:
                              ^
SyntaxError: invalid syntax
>>> 
```

To be continued ...

**Comment by stappersg** [comment]
Yes, with a manual `sudo apt install python3-pip ; sudo pip3 install klaus` I get a _klaus help text_.

Thanks.

For what it is worth: I volunteer to test again when #253 is merged.

**Comment by jonashaag** [comment]
You can install master using `pip install git+https://github.com/jonashaag/klaus`
