### ISSUE TITLE
Klaus Demo is unavailable

### ISSUE THREAD

**Issue by christian-cleberg** [jonashaag/klaus#272]
The [Klaus Demo](http://klausdemo.lophus.org) mentioned in the GitHub repository's sidebar and README does not work. It seems that there is a 500 error occurring.

The error pages specifically notes the following error message: "We're sorry, but something went wrong. If you are the application owner check the logs for more information." See [this screenshot](https://justpaste.it/img/10eee20a5d26459c00e0e27aef5f8bdb.png) for a picture of the error screen.

**Comment by jonashaag** [comment]
Thanks, works now!
