### ISSUE TITLE
OOM error on small repo when cloning/pull

### ISSUE THREAD

**Issue by DUOLabs333** [jonashaag/klaus#276]
I have a very small repo (~1Mb), yet when cloning, git-remote-https gets killed because the system runs out of memory. It's only this repo, all others work fine.

**Comment by jonashaag** [comment]
Can you share the repo?

**Comment by DUOLabs333** [comment]
@jonashaag It's a private repository.

**Comment by masatake** [comment]
Do you use ctags?

**Comment by DUOLabs333** [comment]
No, I don't think so.

**Comment by DUOLabs333** [comment]
> Which version of Dulwich are you using? There have been some fixes recently that improve the strategy for delta resolution - significantly improving memory usage on certain kinds of repository.

I'm using version 0.20.35, which seems to be the latest version.

**Comment by jonashaag** [comment]
Maybe you can send the private repo via email so I can check it out

**Comment by DUOLabs333** [comment]
[homebrew-qemu-virgl-git.tar.gz](https://github.com/jonashaag/klaus/files/8525425/homebrew-qemu-virgl-git.tar.gz)

**Comment by DUOLabs333** [comment]
Correction: this is happening on all but a few of my repos.

**Comment by DUOLabs333** [comment]
@jonashaag So you can recreate this issue with the repo I sent? Does this happen with any of your repos?

**Comment by jonashaag** [comment]
Yes it happens with my repos as well. I wonder if it has something to do with a recent Git release but an older version of Git had the same issue. 

What’s the OS you run git on? I tried macOS only.

**Comment by DUOLabs333** [comment]
This is with Void Linux.

**Comment by DUOLabs333** [comment]
Where is the code for that stored? Maybe I can take a look at it? (Also, maybe you should think of adding an option to use git-http-backend instead).

**Comment by jonashaag** [comment]
The memory leak is in the git-remote-http code

**Comment by DUOLabs333** [comment]
Wouldn't that indicate somethings wrong on the server's side?

**Comment by jonashaag** [comment]
Yes, and/or in Git.

**Comment by jelmer** [comment]
FWIW a number of memory improvements have gone into Dulwich' server gode recently.

**Comment by DUOLabs333** [comment]
Ok, I'll try it out.

**Comment by DUOLabs333** [comment]
The problem seems to remain (dulwich 0.20.45).

**Comment by jonashaag** [comment]
@jelmer any idea what's going on here? I'm facing the same problem now on macOS with the latest Dulwich and Git.

**Comment by jonashaag** [comment]
It starts to happen with Git 2.28. 2.27 is fine.

**Comment by jonashaag** [comment]
Is it related to this? https://github.com/git/git/blob/47ae905ffb98cc4d4fd90083da6bc8dab55d9ecc/Documentation/RelNotes/2.28.0.txt#L91-L93

**Comment by jonashaag** [comment]
@jelmer note that the memory leak is in the *client*

**Comment by jonashaag** [comment]
<img width="549" alt="Screenshot 2023-04-07 at 10 41 29" src="https://user-images.githubusercontent.com/175722/230565154-6a5aef32-7b9b-44c1-ba8c-d031c5349ec9.png">

Git profile

**Comment by jelmer** [comment]
What version of Dulwich do you run on the server side?

**Comment by jelmer** [comment]
Also, is this reproducible with C git an the server side?

**Comment by jelmer** [comment]
Can you reproduce this with git on the server side?

**Comment by jonashaag** [comment]
It works fine with `git daemon --verbose --port=8080 --base-path=. --export-all`.

Anything else I should check?

**Comment by jonashaag** [comment]
I reported a Git bug.

**Comment by jonashaag** [comment]
@jelmer FYI see discussion here. Bug in Git that is about to be fixed. https://lore.kernel.org/git/39035D34-8548-44B0-BBBB-5C36B3876C4A@lophus.org/

**Comment by jelmer** [comment]
Interesting - thanks for the link & background.
