### ISSUE TITLE
How to do lighttpd + klaus?

### ISSUE THREAD

**Issue by fpemud** [jonashaag/klaus#298]

**Comment by fpemud** [comment]
Why is it closed?
Is this possible? Is there any example?

**Comment by jonashaag** [comment]
What exactly is the question?

**Comment by fpemud** [comment]
I used to host klaus using apache.
I'd like to know whether klaus can be hosted using lighttpd that consumes less resource.
I did some searches and found no information or example about it.

**Comment by jonashaag** [comment]
Thanks, now that's a proper question :)

Unfortunately I don't have lots of experience with Apache or lighttpd. Also there's lots of different ways to set up servers so it heavily depends on your use case.

Maybe you can give a little bit more info what's the environment you're hosting in, how many users, is there authentication, ...
