### ISSUE TITLE
Ref names may not contain /

### ISSUE THREAD

**Issue by jonashaag** [jonashaag/klaus#36]
`feature/foo` doesn't work. Bummer.

**Comment by jonashaag** [comment]
This is ready for implementation, see comments in #103

**Comment by stpierre** [comment]
I'm willing to work on this, but I'm not sure what the final conclusion was. #103 makes two suggestions -- URL encoding, and using : as a separator -- and it's not clear which is preferred. A comment in this thread is pretty disdainful of using : as a separator.

One advantage of using : as a separator is that it will work with Gerrit, which is actually my specific use case. Gerrit can integrate with a git browser, but its integration isn't smart enough to be able to URL encode only certain parts of the URL. (That is, you can't tell Gerrit to URL encode the branch name, but not the file path.) So between that, and the ease of implementing : as a separator, I'd lean towards that.

If I can get clear guidance on what the desired implementation is, and if it will work with Gerrit, I'll make it happen.

**Comment by jonashaag** [comment]
At this point I'd actually prefer the GitHub way, that is, doing manual routing here.

So `foo/bar/spam/eggs` could mean `(foo, /bar/spam/eggs)`, `(foo/bar, /spam/eggs)`, `foo/bar/spam, /eggs)` from klaus' point of view.

I'm not sure how difficult this is to implement though -- IIRC the implementation of @posativ in #103 does exactly this. Maybe it is a good starting point.

If that's problematic to implement, I'd go with the `:` suggestion, that is:

- If there's a `:` in the path/branch string, split at the leftmost `:`.
- Otherwise split at the leftmost `/`
- Generate `:` if and only if necessary
