### ISSUE TITLE
git blame equivalent

### ISSUE THREAD

**Issue by jonashaag** [jonashaag/klaus#67]

**Comment by jelmer** [comment]
FWIW https://github.com/jelmer/dulwich/issues/245 tracks blame support in dulwich.

**Comment by jonashaag** [comment]
Thanks, subscribed.

**Comment by jonashaag** [comment]
I'm fine with the implementation above for now (no real plans for switching to libgit2), so if anyone's interested in resurrecting that patch, you're welcome to work on it :-)
