### ISSUE TITLE
Using pull doesn't seem to work with Smart HTTP enabled

### ISSUE THREAD

**Issue by bbqsrc** [jonashaag/klaus#76]
One can clone a repo, but pulling results in the following:
    
    $ git pull
    fatal: git fetch_pack: expected ACK/NAK, got 'dul-daemon says what'

Is this anything that can be solved in klaus or is this a Dulwich fail?

**Comment by jelmer** [comment]
FWIW this should be fixed in Dulwich master.

**Comment by jonashaag** [comment]
Ok, closing
